<?php

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
/** @var $form \Album\Form\AlbumForm */
$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);

// We can use one of two ways to render form elements:
// This one:
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit'));

// and this one:
// echo $this->formCollection($form);

echo $this->form()->closeTag();

