<?php

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
/** @var $form \Album\Form\AlbumForm */
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);

// Wrap the elements in divs marked as form groups, and render
// the label, element, and errors separately within
?>

<div class="form-group">
    <?=$this->formLabel($album)?>
    <?=$this->formElement($album)?>
    <?=$this->formElementErrors()->render($album, ['class' => 'help-block'])?>
</div>

<div class="form-group">
    <?=$this->formLabel($artist)?>
    <?=$this->formElement($artist)?>
    <?=$this->formElementErrors()->render($artist, ['class' => 'help-block'])?>
</div>

<?php
// // We can use one of two ways to render form elements:
// // This one:
// echo $this->formHidden($form->get('id'));
// echo $this->formRow($form->get('title'));
// echo $this->formRow($form->get('artist'));
// echo $this->formSubmit($form->get('submit'));
//
// // and this one:
// // echo $this->formCollection($form);

echo $this->formSubmit($form->get('submit'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

